<?php
/**
 * Created by PhpStorm.
 * User: ckhero
 * Date: 2018/6/11
 * Time: 下午5:33
 */

namespace src\design\template;


class GiftJourney extends Journey
{
    public function enjoyJourney()
    {
        // TODO: Implement enjoyJourney() method.
        return 'Enjoy Journey~!~';
    }

    protected function buyGift()
    {
        //return parent::buyGift(); // TODO: Change the autogenerated stub
        return 'Buy A Gift~!~';
    }
}